from typing import Iterator

class LevelDB:
    def __new__(
            cls,
            path: str,
            create_if_missing=False,
            error_if_exists=False,
            paranoid_checks=False,
            bloom_filter_policy_bits=0,
        ): ...
    def get(self, key: str, verify_checksums=False) -> bytes | None: ...
    def put(self, key: str, value: bytes, sync=False) -> None: ...
    def delete(self, key: str, sync=False) -> None: ...
    def close(self) -> None: ...

    def write(self, ops: dict[str, bytes | None], sync=False) -> None: ...

    def iter(self, start: str | None = None, end: str | None = None, verify_checksums=False) -> Iterator[tuple[str, bytes]]: ...
