from typing import Protocol

class NetworkCallbacks(Protocol):
    def on_ws_data(self, data: bytes) -> None: ...
    def on_kcp_data(self, data: bytes) -> None: ...

class Network:
    def __init__(self, callbacks: NetworkCallbacks) -> None: ...
    @property
    def ws_opened(self) -> bool: ...
    @property
    def ws_closed(self) -> bool: ...
    @property
    def kcp_opened(self) -> bool: ...

    def connect_ws(self, host: str, port: int) -> int: ...
    def connect_kcp(self, host: str, port: int, conv: int, udp_redundancy: int) -> int: ...
    def send_ws(self, data: bytes) -> int: ...
    def send_kcp(self, data: bytes) -> int: ...
    def poll(self) -> None: ...
    def dispose(self) -> None: ...