from typing import Self, Literal, Protocol
from vmath import vec3, vec3i
from godot import PackedVector3Array

TileID = int

class Tile:
    def __new__(cls, _0: TileID, _1: TileID, _2: TileID, _3: TileID): ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, l: int) -> TileID: ...
    def with_l(self, l: int, tile_id: TileID) -> Self: ...

class Tilemap:
    def __new__(cls, width: int, height: int): ...

    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def n_layers(self) -> int: ...

    @property
    def slice_x(self) -> int: ...
    @property
    def slice_y(self) -> int: ...
    @property
    def slice_w(self) -> int: ...
    @property
    def slice_h(self) -> int: ...

    def set(self, x: int, y: int, layer: int, value: TileID) -> None: ...
    def get(self, x: int, y: int, layer: int) -> TileID: ...

    def set_tile(self, x: int, y: int, value: Tile) -> None: ...
    def get_tile(self, x: int, y: int) -> Tile: ...

    def sliced(self, x: int, y: int, w: int, h: int) -> Self: ...


class BodyID:
    @property
    def type(self) -> int: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def id(self) -> int: ...

# DYNAMIC, KINEMATIC, STATIC, TILE
BodyType = Literal[0, 1, 2, 3]

class CollisionCallbacks(Protocol):
    def on_pair_add(self, a: BodyID, b: BodyID, xzl: vec3i, normal: vec3, max_sep: float): ...
    def on_pair_remove(self, a: BodyID, b: BodyID, xzl: vec3i): ...

class Space:
    gravity: vec3
    
    def __new__(cls, tilemap: Tilemap, chunk_size: int, callbacks: CollisionCallbacks): ...

    @property
    def tilemap(self) -> Tilemap: ...
    @property
    def chunk_size(self) -> int: ...

    def step(self, delta: float): ...

    def create_body(self, type: BodyType, aabb_extent: vec3, radius01: float) -> BodyID: ...
    def destroy_body(self, bid: BodyID) -> None: ...
    def teleport_body(self, bid: BodyID, position: vec3) -> None: ...
    def register_tile_body(self, tile_id: TileID, bid: BodyID) -> None: ...
    def remove_pairs_with_tile(self, xzl: vec3i) -> None: ...

    # body properties
    def body_get_layer(self, bid: BodyID) -> int: ...
    def body_set_layer(self, bid: BodyID, layer: int): ...
    def body_get_is_trigger(self, bid: BodyID) -> bool: ...
    def body_set_is_trigger(self, bid: BodyID, is_trigger: bool): ...
    def body_get_mass(self, bid: BodyID) -> float: ...
    def body_set_mass(self, bid: BodyID, mass: float): ...
    def body_get_velocity(self, bid: BodyID) -> vec3: ...
    def body_set_velocity(self, bid: BodyID, velocity: vec3): ...
    def body_get_instant_velocity(self, bid: BodyID) -> vec3: ...
    def body_set_instant_velocity(self, bid: BodyID, velocity: vec3): ...
    def body_get_friction(self, bid: BodyID) -> float: ...
    def body_set_friction(self, bid: BodyID, friction: float): ...
    def body_get_restitution(self, bid: BodyID) -> float: ...
    def body_set_restitution(self, bid: BodyID, restitution: float): ...
    
    def body_get_position(self, bid: BodyID) -> vec3: ...
    def body_get_aabb_extent(self, bid: BodyID) -> vec3: ...
    def body_get_core_extent(self, bid: BodyID) -> vec3: ...
    def body_get_radius(self, bid: BodyID) -> float: ...
    def body_get_radius01(self, bid: BodyID) -> float: ...
    def body_get_chunk_index(self, bid: BodyID) -> int: ...

    def get_ptr(self) -> int: ...


