from typing import Self, Callable, Literal, Protocol
from vmath import vec2, vec2i, vec3, vec3i, vec4i

TileID = int

class Tilemap:
    def __new__(cls, width: int, height: int): ...

    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def n_layers(self) -> int: ...

    @property
    def slice_x(self) -> int: ...
    @property
    def slice_y(self) -> int: ...
    @property
    def slice_w(self) -> int: ...
    @property
    def slice_h(self) -> int: ...

    def set(self, x: int, y: int, layer: int, value: TileID) -> None: ...
    def get(self, x: int, y: int, layer: int) -> TileID: ...

    def setv(self, x: int, y: int, value: vec4i) -> None: ...
    def getv(self, x: int, y: int) -> vec4i: ...

    def sliced(self, x: int, y: int, w: int, h: int) -> Self: ...


class BodyID:
    @property
    def type(self) -> int: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def id(self) -> int: ...

# DYNAMIC, KINEMATIC, STATIC, TILE
BodyType = Literal[0, 1, 2, 3]

class CollisionCallbacks(Protocol):
    def on_pair_add(self, a: BodyID, b: BodyID, xzl: vec3i, normal: vec3 | None): ...
    def on_pair_remove(self, a: BodyID, b: BodyID, xzl: vec3i): ...

class Space:
    def __new__(cls, tilemap: Tilemap, chunk_size: int, callbacks: CollisionCallbacks): ...

    @property
    def tilemap(self) -> Tilemap: ...
    @property
    def chunk_size(self) -> int: ...

    def step(self, delta: float): ...

    def create_body(self, type: BodyType) -> BodyID: ...
    def destroy_body(self, body: BodyID): ...
    def teleport_body(self, body: BodyID, position: vec3): ...
    def remove_pairs_with_tile(self, xzl: vec3i) -> bool: ...

    # body properties
    def body_get_layer(self, body: BodyID) -> int: ...
    def body_set_layer(self, body: BodyID, layer: int): ...
    def body_get_is_trigger(self, body: BodyID) -> bool: ...
    def body_set_is_trigger(self, body: BodyID, is_trigger: bool): ...
    def body_get_mass(self, body: BodyID) -> float: ...
    def body_set_mass(self, body: BodyID, mass: float): ...
    def body_get_velocity(self, body: BodyID) -> vec3: ...
    def body_set_velocity(self, body: BodyID, velocity: vec3): ...
    def body_get_instant_velocity(self, body: BodyID) -> vec3: ...
    def body_set_instant_velocity(self, body: BodyID, velocity: vec3): ...
    
    def body_get_position(self, body: BodyID) -> vec3: ...
    def body_get_extent(self, body: BodyID) -> vec3: ...
    def body_get_size(self, body: BodyID) -> vec3: ...
    def body_get_radius(self, body: BodyID) -> float: ...
    def body_get_chunk_index(self, body: BodyID) -> int: ...
