from typing import Self, Protocol
from vmath import vec3

BodyID = int
TileID = int


class Tilemap:
    def __new__(cls, width: int, height: int, n_layers: int): ...

    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def n_layers(self) -> int: ...

    @property
    def slice_x(self) -> int: ...
    @property
    def slice_y(self) -> int: ...
    @property
    def slice_w(self) -> int: ...
    @property
    def slice_h(self) -> int: ...

    def set(self, x: int, y: int, layer: int, value: TileID): ...
    def get(self, x: int, y: int, layer: int) -> TileID: ...

    def sliced(self, x: int, y: int, w: int, h: int) -> Self: ...



class BodyContext(Protocol):
    pass

class Space:
    def __new__(cls, tilemap: Tilemap, chunk_size: int): ...

    @property
    def tilemap(self) -> Tilemap: ...
    @property
    def chunk_size(self) -> int: ...

    def create_body(self, ctx: BodyContext) -> BodyID: ...
    def destroy_body(self, id: BodyID): ...
    def create_tile(self, x: int, z: int, layer: int, value: TileID): ...
    def destroy_tile(self, x: int, z: int, layer: int): ...

    def get_body_position(self, id: BodyID) -> vec3: ...
    def get_body_velocity(self, id: BodyID) -> vec3: ...

